language: node_js
node_js:
- 8
notifications:
  slack:
    secure: V50CV4yUCMglMIlhkA/ZvBhgZwMdFsEZZ2MS1vpjOlEQaNeZXLwbYcX4bN+QQykdEp85qKad8aGIDgVI2z8FVCs9Ty8dY7bLcmb1wVI7i3mqiWFLzglihmaYpOqCUFgmUEtjmZIqo64fOnpMmWGcO7M+/CPkBDghWjLWvxXtaVS8GJtBLKLaJOqbJuDfl3VSW6VQMT3iNN5xvFiRApUHdhJTzGsh+0ldKYBZnJVHP1DNcO5xUueD5jO6MHDX4/94ICSMidLT2gczo378n23R5YxYpSigK0P8VIghfV6qS9zvoxY/nV54NFpcIHcq8Zp3JFj5ow6HZu50jQpp53/otlg13WVqt/RYrbwe6S9CnD9ftQyzwF/7dQ5tSt0Is8B8stFulRtyUO+lG9/mAugRDFP2WtrPoKYmBbUq7tbFknUPIZS5JETM/jaON3FN3uIN03+LIaED90Fww9qMpTxmrk3VBidoFYls71NU1wNP3Atp7TRUJTRDHYkzxENsFUakJzcLemWA6q7TNI6VAu4mbXoxaNcF0ZuicMwb26EMfmgXwtYAHNYezTGGvKdEEJGhlSIC/8A+xk5YWcAn2Pc3+YH+H5app2j856qw7fLxblOefn+da1Oxv/BS3lFNj+7X1+88jERQ3a/eTk3sYt1GhmhylRetr7VtiOmDs+u0OLc=
